-- Madhav Fast Food - Supabase setup
-- Run this entire file in Supabase SQL Editor.

create table if not exists site_settings (
  id bigint primary key,
  restaurant text default 'Madhav Fast Food',
  village text default 'आपका गाँव',
  phone text default '',
  whatsapp text default '',
  delivery numeric default 20,
  min_order numeric default 0
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order int default 0
);

create table if not exists menu_items (
  id bigint generated by default as identity primary key,
  cat bigint references categories(id) on delete set null,
  name text not null,
  price numeric not null default 0,
  desc text default '',
  image_url text,
  emoji text default '🍽️',
  available boolean default true,
  sort_order int default 0
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  phone text not null,
  village text not null,
  address text not null,
  payment text not null,
  note text default '',
  items jsonb not null,
  subtotal numeric not null,
  delivery numeric default 0,
  total numeric not null,
  status text default 'Order Received'
);

insert into site_settings(id) values (1) on conflict (id) do nothing;

insert into categories(name,sort_order)
select * from (values
 ('Burgers',1),('Pizza',2),('Momos',3),('Chowmein',4),('Fries',5),('Cold Drinks',6)
) v(name,sort_order)
where not exists (select 1 from categories);

insert into menu_items(cat,name,price,desc,emoji,available,sort_order)
select c.id,'Veg Burger',60,'Fresh & tasty veg burger','🍔',true,1 from categories c where c.name='Burgers'
and not exists(select 1 from menu_items where name='Veg Burger');

insert into menu_items(cat,name,price,desc,emoji,available,sort_order)
select c.id,'Cheese Burger',80,'Cheesy and delicious','🍔',true,2 from categories c where c.name='Burgers'
and not exists(select 1 from menu_items where name='Cheese Burger');

insert into menu_items(cat,name,price,desc,emoji,available,sort_order)
select c.id,'Veg Pizza',120,'Loaded with veggies','🍕',true,3 from categories c where c.name='Pizza'
and not exists(select 1 from menu_items where name='Veg Pizza');

insert into menu_items(cat,name,price,desc,emoji,available,sort_order)
select c.id,'Veg Momos',70,'Hot steamed momos','🥟',true,4 from categories c where c.name='Momos'
and not exists(select 1 from menu_items where name='Veg Momos');

insert into menu_items(cat,name,price,desc,emoji,available,sort_order)
select c.id,'Veg Chowmein',80,'Spicy street-style noodles','🍜',true,5 from categories c where c.name='Chowmein'
and not exists(select 1 from menu_items where name='Veg Chowmein');

insert into menu_items(cat,name,price,desc,emoji,available,sort_order)
select c.id,'French Fries',60,'Crispy golden fries','🍟',true,6 from categories c where c.name='Fries'
and not exists(select 1 from menu_items where name='French Fries');

insert into menu_items(cat,name,price,desc,emoji,available,sort_order)
select c.id,'Cold Drink',40,'Chilled soft drink','🥤',true,7 from categories c where c.name='Cold Drinks'
and not exists(select 1 from menu_items where name='Cold Drink');

-- Public website needs read access.
alter table site_settings enable row level security;
alter table categories enable row level security;
alter table menu_items enable row level security;
alter table orders enable row level security;

create policy "public read settings" on site_settings for select using (true);
create policy "public read categories" on categories for select using (true);
create policy "public read menu" on menu_items for select using (true);

-- Customer order creation and status reading.
create policy "public create orders" on orders for insert with check (true);
create policy "public read orders" on orders for select using (true);
create policy "public update orders" on orders for update using (true) with check (true);
create policy "public delete orders" on orders for delete using (true);

-- Owner dashboard writes (password is handled by the site for this simple village deployment).
create policy "public insert menu" on menu_items for insert with check (true);
create policy "public update menu" on menu_items for update using (true) with check (true);
create policy "public delete menu" on menu_items for delete using (true);
create policy "public update settings" on site_settings for update using (true) with check (true);

-- Storage bucket for food images.
insert into storage.buckets (id,name,public) values ('food-images','food-images',true)
on conflict (id) do update set public=true;

create policy "public image upload" on storage.objects for insert with check (bucket_id='food-images');
create policy "public image read" on storage.objects for select using (bucket_id='food-images');
create policy "public image update" on storage.objects for update using (bucket_id='food-images') with check (bucket_id='food-images');
create policy "public image delete" on storage.objects for delete using (bucket_id='food-images');
